#!/bin/sh

unset BMAIL_DOMAIN
unset BMAIL_SPOOL
unset BMAIL_USER
unset BMAIL_GROUP

if [ -z "$BMAILRC" ]; then
	BMAILRC="/etc/bmailrc"
fi

if [ -r "$BMAILRC" ]; then
	set -a
	. "$BMAILRC"
	set +a
fi

exec bmaild

